// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowerAppsUIValues;

#nullable disable

namespace PowerAppsUIValues.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250719192805_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("PowerAppsUIValues.Models.UISchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundColorPrimary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColorSecondary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColorTertiary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColorTertiaryDark")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColorTertiaryLight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryFontFamily")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryFontFamily")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TertiaryFontFamily")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextColorPrimary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextColorSecondary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextColorTertiary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextColorTertiaryDark")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextColorTertiaryLight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UISchemas");
                });
#pragma warning restore 612, 618
        }
    }
}
